require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/ParameterLists:
  Max: 7

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
